import org.jetbrains.changelog.Changelog

plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.16.3' apply false
    id 'net.neoforged.moddev' version '2.0.137' apply false
    id 'org.jetbrains.changelog' version '2.2.1'
    id "me.modmuss50.mod-publish-plugin" version "2.2.0"
}

changelog {
    version = version
    path = file("CHANGELOG.md").canonicalPath
    groups = ["Added", "Changed", "Deprecated", "Removed", "Fixed", "Security"]
    lineSeparator = "\n"
}

publishMods {
    type = STABLE
    version = "${project.version}+${minecraft_version}"
    changelog = project(":common").changelog.renderItem(project(":common").changelog
            .getLatest()
            .withHeader(false)
            .withEmptySections(false),
            Changelog.OutputType.MARKDOWN
    )
    def cfOptions = curseforgeOptions{
        projectId = "1469248"
        projectSlug = "emidiscovery" // Required for discord webhook
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        minecraftVersions.add(project.minecraft_version)
        javaVersions.add(JavaVersion.VERSION_21)
        clientRequired = true
        serverRequired = true
        requires("cloth-config")
        optional("reliable-emi")
    }
    def mrOptions = modrinthOptions{
        projectId = "WO3G3DRj"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add(project.minecraft_version)
        requires("cloth-config")
        optional("reliable-emi")
    }

    curseforge("curseforgeFabric"){
        from cfOptions
        file project(":fabric")
        modLoaders.add("fabric")
        optional("modmenu")
    }

    curseforge("curseforgeNeoForge"){
        from cfOptions
        file project(":neoforge")
        modLoaders.add("neoforge")
    }

    modrinth("modrinthFabric") {
        from mrOptions
        file project(":fabric")
        modLoaders.add("fabric")
        optional("modmenu")
    }

    modrinth("modrinthNeoForge") {
        from mrOptions
        file project(":neoforge")
        modLoaders.add("neoforge")
    }
}