plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    compileOnly project(":common")
    implementation 'org.jetbrains:annotations:25.0.0'
    api("me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}")
    implementation "dev.emi:emi-neoforge:${emi_version}"
    implementation "maven.modrinth:reliable-emi:${remi_version}-${minecraft_version}-neoforge"
    runtimeOnly "maven.modrinth:yacl:${yacl_version}+${minecraft_version}-neoforge"
}

publishMods {
    file = tasks.named("jar").flatMap { it.archiveFile }
}
